### ISSUE TITLE
Неверное определение следующей серии

### ISSUE THREAD

**Issue by Mogost** [Kraigo/myshows-recent#2]
![image](https://user-images.githubusercontent.com/721963/90312446-2fef4400-df0d-11ea-9ec5-1c4b12655461.png)
Предлагает отметить 5 серию, хотя есть 2.
 Версия расширения 2.0.4

**Comment by Kraigo** [comment]
Похоже что это происходит из-за того, что серии вышли в один день.

**Comment by Kraigo** [comment]
Fixed in version 2.1.2
